const STORAGE_NAME = "@scmanager";

const STORAGE_TOKEN = `${STORAGE_NAME}/token`;
const STORAGE_REFRESHTOKEN = `${STORAGE_NAME}/refresh`;

const STORAGE_THEME = `${STORAGE_NAME}/theme`;

const STORAGE_POST_MANAGEMENT =`${STORAGE_NAME}/postManagement`;

export { STORAGE_TOKEN, STORAGE_REFRESHTOKEN, STORAGE_THEME, STORAGE_POST_MANAGEMENT };
