export const API_ACCOUNT = {
  BUILD: () => `/Account/Build`,
  PREPARE: () => `/Account/Prepare`,
  LOGIN: () => `/Account/Login`,
  REFRESH: () => `/Account/Refresh`,
  CONFIRMACCOUNT: () => `/Account/ConfirmAccount`,
  FORGOTPASSWORD: () => `/Account/ForgotPassword`,
  RESETPASSWORD: () => `/Account/ResetPassword`,
  CREATE: () => `/Account/Create`,
  SAVE: () => `/Account/Save`,
  GETBYID: () => `/Account/GetById`,
  DELETE: () => `/Account/Delete`,
  GETROLES: () => `/Account/GetRoles`,
  RESETPASSWORDSIGNIN: () => `/Account/ResetPasswordSignIn`,
  RESENDEMAILCONFIRMATION: () => `/Account/ResendEmailConfirmation`,
  GETALL: () => `/Account/GetAll`,
  USERINFO: () => `/Account/UserInfo`,
};
